// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ63teiApoAbWV4R5c9JvLqxWu7j0TgDI',
    appId: '1:919344833101:web:029fc9240bf3e794ef7204',
    messagingSenderId: '919344833101',
    projectId: 'kvanaparthi-cmsc5303-flu-db993',
    authDomain: 'kvanaparthi-cmsc5303-flu-db993.firebaseapp.com',
    storageBucket: 'kvanaparthi-cmsc5303-flu-db993.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4zdvo285T-NFBdmgdojtC_KXRDWH0jh4',
    appId: '1:919344833101:android:8c5cc87b16cb1bb1ef7204',
    messagingSenderId: '919344833101',
    projectId: 'kvanaparthi-cmsc5303-flu-db993',
    storageBucket: 'kvanaparthi-cmsc5303-flu-db993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnaO5cV6AGvAKyxZ8RfS7DlW54lm-lanw',
    appId: '1:919344833101:ios:77389137533a1283ef7204',
    messagingSenderId: '919344833101',
    projectId: 'kvanaparthi-cmsc5303-flu-db993',
    storageBucket: 'kvanaparthi-cmsc5303-flu-db993.appspot.com',
    iosBundleId: 'edu.uco.kvanaparthi.cmsc5303.lesson6',
  );

}